# Generated by Django 6.0 on 2026-01-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_rename_eloparamenter_eloparameter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="first_name",
            new_name="nickname",
        ),
    ]
