# Generated by Django 6.0 on 2026-01-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_rename_first_name_player_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
