# Generated by Django 6.0 on 2026-01-23 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_player_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="eloparameter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eloparameter",
            name="scale_factor",
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
