# Generated by Django 5.2.9 on 2025-12-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_one', models.IntegerField()),
                ('score_two', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_player_one', to='website.player')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_player_two', to='website.player')),
            ],
        ),
    ]
