# Generated by Django 5.1.6 on 2025-12-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_match_id_alter_player_id_ratingrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingrecords',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.match'),
        ),
    ]
