# Generated by Django 5.1.6 on 2025-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_ratingrecords_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloParamenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_index', models.IntegerField()),
                ('start_elo', models.IntegerField()),
            ],
        ),
    ]
