# Generated by Django 5.1.6 on 2025-12-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_eloparamenter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EloParamenter',
            new_name='EloParameter',
        ),
    ]
